server:
  port: 10000
  address: 0.0.0.0
  max-http-header-size: 20480

logging:
  format: text

mission-control:
  web:
    cors:
      allowed-origins:
        - "*"
        - "http://localhost"

    cookies:
      domain: localhost
      secured: false

    auth:
      type: IN_MEMORY
      in-memory:
        users:
          - name: admin
            password: admin
            roles: ROLE_READER, ROLE_ADMIN

    tokens:
      default-lifetime-seconds: 864000
      issuer: mission-control
      secret: development-environment-jwt-secret

    anonymous:
      roles: ROLE_ANONYM

    roles:
      - name: ROLE_ANONYM
        grants: read_clusters, read_deployments
      - name: ROLE_READER
        inherits: ROLE_ANONYM
      - name: ROLE_ADMIN
        inherits: ROLE_READER
      - name: NA-INT-MISSION-CONTROL-WEB
        inherits: ROLE_READER

  frontend:
    serve:
      enable: true
      directory: /opt/mission-control-spa/
    config:
      site:
        metrics:
          yandex-metrika:
            enable: true
            account: 68726251
        features:
          show_login_button: false
          show_deployment_endpoints: true

  tokens-source:
    type: kubeconfig
    kubeconfig:
      path: "~/.kube/config"
      aliases:
        testing: "kubernetes.testing.example.com"
        prod: "kubernetes.production.example.com"

  clusters:
    - name: testing
      displayName: "TESTING A"
      host: "https://kubernetes.testing.example.com:6443"
      dc: "datacenter-name"
    - name: prod
      displayName: "PROD A"
      host: "https://kubernetes.production.example.com:6443"
      dc: "datacenter-name"

spring:
  cloud:
    discovery:
      client:
        composite-indicator.enabled: false

management:
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    vault.enabled: false
    ldap.enabled: false
    discoveryComposite.enabled: false
    diskSpace.enabled: false
    refresh.enabled: false
