name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Export env variables
      run: |
        echo 'APP_VERSION='"$(cat ./VERSION)"
        echo 'IMAGE_PREFIX=${{ github.repository_owner }}/mission-control'
        echo 'IMAGE_TAG_LATEST='"$IMAGE_PREFIX:latest"
        echo 'IMAGE_TAG='"$IMAGE_PREFIX:$APP_VERSION"
    - name: Build the JAR
      run: gradle build
    - name: Build the Docker image
      run: docker build . --tag $IMAGE_TAG_LATEST --tag $IMAGE_TAG
    - name: Push the Docker image
      run: docker push $IMAGE_TAG_LATEST $IMAGE_TAG
